spring:
    r2bc:
        driver: pool
        protocal: mysql
        host: localhost
        port: 3306
        username: root
        password: 123456
        database: flux-api-demo
        max-size: 10
