spring:
    r2dbc:
        url: r2dbc:mysql://localhost:3306/react-demo?useUnicode=true
        username: root
        password: 123456
        name: r2dbc
        pool:
            validation-query: SELECT 1
            enabled: true